# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activites',
            options={'verbose_name_plural': 'Activites'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name_plural': 'Degree'},
        ),
        migrations.AlterModelOptions(
            name='departmentnews',
            options={'verbose_name_plural': 'Department News'},
        ),
        migrations.AlterModelOptions(
            name='departmentphotos',
            options={'verbose_name_plural': 'Department Photos'},
        ),
        migrations.AlterModelOptions(
            name='electives',
            options={'verbose_name_plural': 'Electives'},
        ),
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='facultyroles',
            options={'verbose_name_plural': 'Faculty Roles'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'verbose_name_plural': 'Programmes'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
    ]
