# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20180201_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
