# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20180201_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('S', 'Sessional')], default='L', max_length=30),
        ),
    ]
