# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20180201_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyroles',
            name='department',
        ),
    ]
