# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20180131_1814'),
        ('department', '0004_auto_20180131_1820'),
    ]

    operations = [
    ]
